version: "2.1"
services:
  localstack:
    image: localstack/localstack
    container_name: pr_spike_s3
    ports:
      - "4566:4566" # port of to where localstack can be addressed to
      - "9999:9000"
    environment:
      - SERVICES=s3 # a list of desired services you want to use.
      - DEFAULT_REGION=us-east-1 # This is the region where your localstack mocks to be running
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9999
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1